# SNAP Gap in Los Angeles County: Spatial Patterns and Predictors
#### Meaghan Woody


## Urban Planning 213 Final Project 

#### **Background:**

One of the most urgent priorities for anti-hunger nonprofit organizations and CalFresh agencies in California is targeted outreach to eligible but unenrolled households. However, few tools exist to systematically identify communities where enrollment is low, even though need is high. “SNAP Gap” refers to the proportion of those who are eligible but not enrolled in Federally funded Supplemental Nutrition Assistance Program (SNAP). California ranks significantly lower than half the US (81% in 2022, 67% in 2020), yet has the highest number of SNAP recipients (USDA, 2022). In 2020, it was reported there is an estimated 280,000 LA County households who remain eligible for but are not receiving CalFresh. In general, to get CalFresh benefits, the household's gross income must be less than the gross-income eligibility standard 130% of the Federal Poverty Level (FPL).

Understanding neighborhood-level aspects of SNAP participation can greatly inform outreach efforts. Mapping tools can help identify and share opportunities to maximize efforts by targeting local areas with the lowest participation rates. Low SNAP participation rates in California cannot be attributed to a single factor but rather a multitude of factors that span across policy, politics, administration, demographics, and cultural attitudes, therefore this project aims to identify predictors of SNAP gap through an exploratory analysis. 

#### **Research aims:** 

1. Map the distribution of SNAP gap and food insecurity in Los Angeles County in varying geographic units.
2. Conduct a cluster analysis using SNAP gap and SNAP participation rates
3. Identify predictors that explain SNAP gap using machine learning models trained on American Community Survey (ACS) variables.

#### **References:**

1. U.S. Department of Agriculture, Food and Nutrition Service. (2025, April 18). Reaching those in need: Estimates of state SNAP participation rates in 2022. https://www.fns.usda.gov/research/snap/state-participation-rates/2022
2. Los Angeles Regional Food Bank. (n.d.). Closing the SNAP Gap. Retrieved June 11, 2025, from https://www.lafoodbank.org/stories/closing-the-snap-gap/#:~:text=The%20gap%20during%202019%20was,pandemic%2C%20a%20gap%20still%20remains. https://www.lafoodbank.org/closing-the-snap-gap/.

#### **Workflow of notebooks:**

`0_Project intro & Data prep`: Prepping dataset: pull data from American Community Survey, variable creation, and join with spatial data

`1_Mapping SNAP Rates`: Aims 1 and 2

`2_Machine Learning`: Aim 3

### 1) Access Census Data using the Census Bureau API

The table below shows all the variables needed to be pulled from the American Community Survey (2023) through the Census Bureau API.

The variable names can be accessed at here: https://api.census.gov/data/2023/acs/acs5/variables.html. ACS specifies the denominator for most variables. The variables we will use in analysis will be rates. 

There are more variables that could be investigated in the future that were not added in this analysis, such as English language proficiency, single parent households, disability, and household with children and elderly.

| **ACS Description** | **Numerator Var** | **Denominator Var** | **New Variable Name** |
|---------------------|-------------------|----------------------|------------------------|
| **== Demographics ==** | | | |
| Foreign-born: Not a U.S. citizen | B05002_021E | B05002_013E | %_foreignborn |
| Population aged 65+ (males + females) | B01001_020E to B01001_025E, B01001_044E to B01001_049E | B01001_002E + B01001_026E | %_seniors |
| Hispanic or Latino | B03003_003E | B03003_001E | %_hispanic |
| Black or African American alone | B02001_003E | B02001_001E | %_black |
| Asian alone | B02001_005E | B02001_001E | %_asian |
| **== Socioeconomics ==** | | | |
| Income < 0.50 FPL | C17002_002E |  | part of snap |
| Income 0.50–0.99 FPL | C17002_003E |  | part of snap |
| Income 1.00–1.24 FPL | C17002_004E |  | part of snap |
| Income 1.25–1.49 FPL | C17002_005E |  | part snap |
| Median household income | B19013_001E | N/A | median_income |
| Employed (age 16+) | B23025_004E | B23025_002E | %_employed |
| Enrolled in college, undergraduate years | B14001_008E | B14001_002E | %_undergrad |
| **== Household ==** | | | |
| Average household size | B25010_001E | N/A | avg_hh_size |
| Renter occupied housing units | B25003_003E | B25003_001E | %_renters |
| Rent burdened (30% or more of income) | B25070_007E to B25070_010E | B25070_001E | %_rent_burd |
| No Internet access | B28002_013E | B28002_001E | %_no_int |
| No vehicle | B25044_003E | B25044_001E | %_no_vehic |
| **== SNAP ==** | | | |
| Household did not receive SNAP, income < FPL | B22003_006E | C17002_002E+C17002_003E+C17002_004E+C17002_005E | snap_ebne |
| (ALL) Household received SNAP | B22003_002E | C17002_002E+C17002_003E+C17002_004E+C17002_005E | snap_rate |

Use the Census API to request all the variables in the table above for Los Angeles County (0637) tracts.

In [6]:
import json
import requests
import pandas as pd

r = requests.get(
    "https://api.census.gov/data/2023/acs/acs5?"
    "get=B05002_021E,B05002_013E,"
    "B01001_002E,B01001_026E,"
    "B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,"
    "B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E,"
    "B03003_003E,B03003_001E,"
    "B02001_003E,B02001_005E,B02001_001E,"
    "C17002_001E,C17002_002E,C17002_003E,C17002_004E,C17002_005E,"
    "B19013_001E,"
    "B23025_004E,B23025_002E,"
    "B14001_008E,B14001_002E,"
    "B25010_001E,"
    "B25003_003E,B25003_001E,"
    "B25070_007E,B25070_008E,B25070_009E,B25070_010E,B25070_001E,"
    "B28002_013E,B28002_001E,"
    "B25044_003E,B25044_001E,"
    "B22003_006E,B22003_002E,B22003_001E"
    "&for=tract:*&in=state:06%20county:037"
)
censusdata = r.json()
census_snap = pd.DataFrame(censusdata[1:], columns=censusdata[0])
census_snap.head(2)

,B05002_021E,B05002_013E,B01001_002E,B01001_026E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,...,B28002_013E,B28002_001E,B25044_003E,B25044_001E,B22003_006E,B22003_002E,B22003_001E,state,county,tract
0,347,1608,2035,2117,101,120,55,50,63,16,...,125,1558,59,1558,144,283,1558,06,037,101110
1,347,2122,2130,2068,49,66,149,54,32,115,...,19,1407,0,1407,27,160,1407,06,037,101122

Below shows the calculation of all the rates that will be used for analysis.

In [8]:
# Calculate rate percentages using the global denominator denoted by ACS for each variable
# Convert variables to float in variable calculations

# == Demographics ==
census_snap['%_foreignborn'] = (census_snap['B05002_021E'].astype(float) / census_snap['B05002_013E'].astype(float)) * 100

seniors_num = (census_snap[['B01001_020E', 'B01001_021E', 'B01001_022E', 'B01001_023E', 'B01001_024E', 'B01001_025E',
                                 'B01001_044E', 'B01001_045E', 'B01001_046E', 'B01001_047E', 'B01001_048E', 'B01001_049E']]
                     .astype(float).sum(axis=1))
                     # Sum of males age>65 (B01001_020E to B01001_025E) and females age>65 (B01001_044E to B01001_049E)
seniors_denom = census_snap['B01001_002E'].astype(float) + census_snap['B01001_026E'].astype(float)
                     # Sum of all males and all females
census_snap['%_seniors'] = (seniors_num / seniors_denom) * 100

census_snap['%_hispanic'] = (census_snap['B03003_003E'].astype(float) / census_snap['B03003_001E'].astype(float)) * 100
census_snap['%_black'] = (census_snap['B02001_003E'].astype(float) / census_snap['B02001_001E'].astype(float)) * 100
census_snap['%_asian'] = (census_snap['B02001_005E'].astype(float) / census_snap['B02001_001E'].astype(float)) * 100

# == Socioeconomics ==
poverty = (census_snap['C17002_002E'].astype(float) + census_snap['C17002_003E'].astype(float) + 
                      census_snap['C17002_004E'].astype(float) + census_snap['C17002_005E'].astype(float))
                    # Sum of income groups 150% FPL (for SNAP rates) 

census_snap['%_employed'] = (census_snap['B23025_004E'].astype(float) / census_snap['B23025_002E'].astype(float)) * 100
census_snap['%_undergrad'] = (census_snap['B14001_008E'].astype(float) / census_snap['B14001_002E'].astype(float)) * 100

# == Household ==
census_snap['%_renters'] = (census_snap['B25003_003E'].astype(float) / census_snap['B25003_001E'].astype(float)) * 100

rent_burd_num = census_snap[['B25070_007E', 'B25070_008E', 'B25070_009E', 'B25070_010E']].astype(float).sum(axis=1)
                  # Rent burdened sum rent over 30% of income)
census_snap['%_rent_burd'] = (rent_burd_num / census_snap['B25070_001E'].astype(float)) * 100

census_snap['%_no_int'] = (census_snap['B28002_013E'].astype(float) / census_snap['B28002_001E'].astype(float)) * 100
census_snap['%_no_vehic'] = (census_snap['B25044_003E'].astype(float) / census_snap['B25044_001E'].astype(float)) * 100

# == SNAP ==
census_snap['snap_ebne'] = (census_snap['B22003_006E'].astype(float) / poverty) * 100
census_snap['snap_rate'] = (census_snap['B22003_002E'].astype(float) / poverty) * 100

# Only renaming is needed for two variables that do not have denominators 
census_snap['median_income'] = census_snap['B19013_001E'].astype(float)
census_snap['avg_hh_size'] = census_snap['B25010_001E'].astype(float)

# View new variables
census_snap.head(2)

,B05002_021E,B05002_013E,B01001_002E,B01001_026E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,...,%_employed,%_undergrad,%_renters,%_rent_burd,%_no_int,%_no_vehic,snap_ebne,snap_rate,median_income,avg_hh_size
0,347,1608,2035,2117,101,120,55,50,63,16,...,93.125811,32.312253,48.780488,52.50000,8.023107,3.786906,23.300971,45.792880,84091.0,2.60
1,347,2122,2130,2068,49,66,149,54,32,115,...,90.264317,31.619537,22.103767,69.77492,1.350391,0.000000,6.601467,39.119804,99583.0,2.98

In [9]:
# Check the raw proportions of SNAP gap and SNAP enrollment
census_snap['snap_ebne'].describe()
census_snap['snap_rate'].describe()

count    2468.000000
mean       21.289411
std        13.223573
min         0.000000
25%        13.126501
50%        19.184413
75%        26.826806
max       141.666667
Name: snap_rate, dtype: float64

It looks like SNAP rate has values greater than 100%, which is not valid. This occurred because the numerator (households >100% FPL not enrolled in SNAP) can exceed the denominator (households >150% FPL), especially in low-income areas, leading to inflated ratios. To correct this, the SNAP rate can be capped at 100%.

In [11]:
# Clip snap gap at 100%
census_snap['snap_rate'] = census_snap['snap_rate'].clip(upper=100)
census_snap['snap_rate'].describe()

count    2468.000000
mean       21.245612
std        12.906688
min         0.000000
25%        13.126501
50%        19.184413
75%        26.826806
max       100.000000
Name: snap_rate, dtype: float64

In [12]:
# Check for missing values
census_snap['snap_ebne'].isna().sum() 
census_snap['snap_rate'].isna().sum()

# 30 tracts have missing values. This is a marginal proportion and should not mess up any calculation.

30

### 2) Load in Shapefiles for Los Angeles County

Join the American Community Survey variables with shape files for mapping in the next step. 

Data obtained from https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html
& https://www.census.gov/cgi-bin/geo/shapefiles/index.php

In [14]:
import geopandas as gpd

# Load LA County tract shapefile
tracts = gpd.read_file('/Users/markwoody/Desktop/UP 213/UP213Final/final/data/tl_2020_06037_tract20')
print(tracts.columns)
tracts.head(5)

# Create GEOID in both datasets
census_snap['GEOID'] = census_snap['state'] + census_snap['county'] + census_snap['tract']
tracts['GEOID'] = tracts['GEOID20']

# Set GEOID as index
tracts = tracts.set_index('GEOID')
census_snap = census_snap.set_index('GEOID')

# Join geometry from tracts into full census_snap
snap_tracts = census_snap.join(tracts[['geometry']], how='inner')
snap_tracts = gpd.GeoDataFrame(snap_tracts, geometry='geometry', crs='EPSG:4326')
snap_tracts.head(2)

Index(['STATEFP20', 'COUNTYFP20', 'TRACTCE20', 'GEOID20', 'NAME20',
       'NAMELSAD20', 'MTFCC20', 'FUNCSTAT20', 'ALAND20', 'AWATER20',
       'INTPTLAT20', 'INTPTLON20', 'geometry'],
      dtype='object')

,B05002_021E,B05002_013E,B01001_002E,B01001_026E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,...,%_undergrad,%_renters,%_rent_burd,%_no_int,%_no_vehic,snap_ebne,snap_rate,median_income,avg_hh_size,geometry
GEOID,,,,,,,,,,,,,,,,,,,,,
06037101110,347,1608,2035,2117,101,120,55,50,63,16,...,32.312253,48.780488,52.50000,8.023107,3.786906,23.300971,45.792880,84091.0,2.60,"POLYGON ((-118.30229 34.2587, -118.30091 34.25..."
06037101122,347,2122,2130,2068,49,66,149,54,32,115,...,31.619537,22.103767,69.77492,1.350391,0.000000,6.601467,39.119804,99583.0,2.98,"POLYGON ((-118.30334 34.27371, -118.3033 34.27..."

Save this dataset so we can use it in the next notebook for mapping.

In [16]:
snap_tracts.to_file("snap_tracts_exp.gpkg", driver="GPKG")